source:
  connection_uri: $DATABASE_URL
  tables:
    - name: providers
      transform:
        - identifier: reverse
          first_name: first-name
          last_name: last-name
store:
  bucket: nw-data-transfer
  aws_access_key_id: $AWS_ACCESS_KEY_ID
  aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
destination:
  connection_uri: postgres:://postgres:postgres@localhost:5432/northwest
