#!/bin/bash

set -euo pipefail

LAST_RELEASE=`gh release list | head -1 | awk '{print $1}'`
cargo build --release

cd target/release
zip "joindoe_${LAST_RELEASE}_arm64-apple-darwin.zip" joindoe
shasum -a 256 "joindoe_${LAST_RELEASE}_arm64-apple-darwin.zip" > "joindoe_${LAST_RELEASE}_arm64-apple-darwin.zip.sha256sum"

gh release upload "$LAST_RELEASE" "joindoe_${LAST_RELEASE}_arm64-apple-darwin.zip"
gh release upload "$LAST_RELEASE" "joindoe_${LAST_RELEASE}_arm64-apple-darwin.zip.sha256sum"
cd -

echo Done.
